import discord

def bothelp(cat : str):
  if cat!=None:
    cat=cat.lower()
    cat=cat.replace(" ","")
    cat=cat.replace("-","")
    cat=cat.replace("_","")
  if cat=="basic" or cat=="simple" or cat=="normal" or cat=="regular" or cat=="core":
    ti="Basic Commands"
    desc="""
**help {Command or Category}**
Show the help for a specific command/category. The command/category is optional.

**invite**
Invites the bot to your server.

**prefix {New prefix}**
View or change the prefix of the bot.

**ping**
Checks the speed of the bot.

**speedtest**
Does the `ping` command 5 times, thus more accurate.
  """
  elif cat=="discordinfo" or cat=="discordinformation" or cat=="discordi":
    ti="Discord Information Commands"
    desc="""
**server**
Shows information about the current server.

**role [Role ID or Mention]**
Shows information about the desired role.

**channel {Channel Name or ID}**
Shows information about the desired channel.

**voicechannel [Channel Name or ID]**
Shows information about the desired Voice Channel.

**user [User Name, Nickname, ID or Mention] [Channel Name, ID or Mention]**
Shows information about the desired User in a specific channel.
The arguments are optional.

**uservoice [User Name, Nickname, ID or Mention] [Channel Name or ID]**
Shows information about the desired User in a specific voice channel.

**avatar {User Name, Nickname, ID or Mention}**
Shows the avatar of the desired user.

**voicechannel [Invite link or ID]**
Shows information about the desired invite link.

**template [Template ID]**
Shows information about the desired server template.
This command is still in BETA.
  """
  elif cat=="discord":
    ti="Discord Commands"
    desc="""
**spam [Number of times to spam] [Text to spam]**
Spams the text.
It must be less than 30 times and without any mentions.

**embed [Title] [Description] [Color] [Author] [Author URL] [Author Image URL] [Footer] [Thumbnail Image URL] [Image URL]…**
Generates an embed.
**One line for each argument.**
Please check the [documentation](https://github.com/johann-lau/Bot#embed-message-help) for more information.

**pretend [User Name, Nickname, ID or Mention] [Text]**
Pretends as a user and send something, using the magic of webhooks.

**pretendembed [User Name, Nickname, ID or Mention] [Title] [Description] [Color] [Author] [Author URL] [Author Image URL] [Footer] [Thumbnail Image URL] [Image URL]…**
Pretends as a user and generates an embed.
**One line for each argument.**
Please check the [documentation](https://github.com/johann-lau/Bot#embed-message-help) for more information.

**pretendspam [User Name, Nickname, ID or Mention] [Text]**
Pretends as a user and spams the text.
It must be less than 30 times and without any mentions.
  """
  elif cat=="text" or cat=="textmanipulation" or cat=="manipulation":
    ti="Text Manipulation Commands"
    desc="""
**insert [Emoji] [Text]**
Replaces the spaces in the text with emojis.
Protip: also works with multiple emojis by wrapping all emojis in quotation marks. E.g. `=insert ":thumbsup: :heart:" I love this bot!`

**spoiler [Text]**
Generates an annoying spoiler.

**rawspoiler [Text]**
Generates an annoying spoiler for you to copy and paste.

**reverse [Text]**
sesrever the provided text.

**emoji [Text]**
Generates emoji text.
Supported characters: A-Z a-z 0-9 ! ? $ # * + - × ÷
  """
  elif cat=="moderation" or cat=="moderate" or cat=="moderator" or cat=="administer" or cat=="administration" or cat=="administrator" or cat=="manage" or cat=="management" or cat=="manager":
    ti="Moderation Commands"
    desc="""
**kick [User Name, Nickname, ID or Mention] {Reason}**
Kicks a desired user. The Reason is optional.

**ban [User Name, Nickname, ID or Mention] {Reason}**
Bans a desired user. The Reason is optional.

**slowmode [Seconds] {Channel(s)}**
Sets the slowmode for the channel. Any non-numeric value, or zero, disables it.
Channels is optional. If Channel(s) is not provided, the current channel will be set.\nYou are allowed to use multiple channels, or use `all` to set for all channels in the server.
  """
  elif cat=="information" or cat=="info" or cat=="informative":
    ti="Information Commands"
    desc="""
**calc [Formula]**
Does boring math for you. Logical comparisons, scientific math, variables and user-defined functions are available. Please check the [documentation](https://github.com/johann-lau/Bot/blob/main/README.md#math-help) for more information.

**define [name] [definition] [arguments separated by spaces]**
Defines a custom function. Please check the [documentation](https://github.com/johann-lau/Bot/blob/main/README.md#math-help) for more information.

**time {Timezone}**
Checks the time in your timezone. If Timezone is not specified, you will see the UTC time.

**rtimer [Time to count] {Text}**
Starts a timer. Please see the help command for more information.

**terminate [Timer ID]**
Properly terminates a running timer generated by `rtime`.
The Timer ID is a random 5-alphabet code and can be found at the beginning of a timer.

**translate [To language]{,From language} [Text]**
Translates text to another language. If From language is not provided, it will detect the language. e.g. `=translate en Ahoj` `=translate en,cs Ahoj`
  """
  elif cat=="web" or cat=="link" or cat=="url" or cat=="website":
    ti="Web Commands"
    desc="""
**screenshot [URL]**
Screenshots the desired webpage. A regular-sized screenshot and a whole-webpage-sized screenshot will be shown.

**youtube [URL]**
Downloads a youtube video and the captions. If the video size is larger than 8MB, only the captions will be uploaded.

**wiki [Query]**
Finds a related Wikipedia article.

**engrave [Product] [Text]**
Engraves the text on an Apple Product. Airpods, iPad, iPod and Apple Pencil are available. Please check the [documentation](https://github.com/johann-lau/Bot/blob/main/README.md#apple-engrave-help) for more information.

**covid {Country}**
Fetches the Covid-19 status for a specific country. If no country is specified, it will fetch the data of the whole World.

**population {Country}**
Fetches the Population statistics for a specific country. If no country is specified, it will fetch the data of the whole World.
"""

  elif cat=="developer" or cat=="tools" or cat=="misc" or cat=="other" or cat=="others" or cat=="extras":
    ti="Developer Tools"
    desc="""
**python [Script]**
Executes a Python (3.9.1) script.

**transparent [Image] {Transparency Level}**
Makes an image transparent with the transparency level (between 0 and 255).

**ocr [Image]**
Does an OCR scan for the image.

**text [PDF]**
Turns the PDF to plain text.

**html [HTML Code]**
Screenshots an HTML code.

**md [Markdown Code]**
Screenshots a Markdown code.

**regex [Regex] [Text]**
Check for text occurrences for a Regular Expression.

**regsub [Regex 1] [Regex 2] [Text]**
Find Regex 1 in text, then replace with Regex 2.
"""
  elif cat=="plot" or cat=="plotting" or cat=="chart" or cat=="graph":
    ti="Web Command and Developer Tools"
    desc="""
**pie [Data] [Title] [Labels]**
Plots a pie chart with the Title (e.g. "Popularity of different fruits"), Data (e.g. 1,2,3,4) and Labels (e.g. Apple,Banana,Cherry,Date).

**barh [Data] {Title}**
Plots a **h**orizontal [bar chart](https://en.wikipedia.org/wiki/Bar_chart) with the Title (e.g. "Popularity of different fruits"), Data (e.g. 1,2,3,4) and Labels (e.g. Apple,Banana,Cherry,Date).

**barv [Data] {Title}**
Plots a **v**ertical [bar chart](https://en.wikipedia.org/wiki/Bar_chart) with the Title (e.g. "Popularity of different fruits"), Data (e.g. 1,2,3,4) and Labels (e.g. Apple,Banana,Cherry,Date).

**hist [Data] {Title}**
Plots a 1-dimensional [histogram](https://en.wikipedia.org/wiki/Histogram) with the Data (e.g. 1,2,2,3,3,3,4,4,5).

**snow {Recursion}**
Plots a [Koch Snowflake](https://en.wikipedia.org/wiki/Koch_snowflake) with the recursion (max. 10). In general, the higher the recursion, the more beautiful the output.
"""
  elif cat=="help":
    ti="help {Command or Category}"
    desc="Show the help for a specific command/category. The command/category is optional."
  elif cat=="invite":
    ti="invite"
    desc="Invites the bot to your server."
  elif cat=="prefix":
    ti="prefix"
    desc="View the prefix of the bot."
  elif cat=="ping":
    ti="ping"
    desc="Checks the speed of the bot."
  elif cat=="speedtest":
    ti="speedtest"
    desc="Does the `ping` command 5 times, thus more accurate."
  elif cat=="server":
    ti="server"
    desc="Shows information about the current server."
  elif cat=="role":
    ti="role [Role ID or Mention]"
    desc="Shows information about the desired role."
  elif cat=="channel":
    ti="channel {Channel Name, ID or Mention}"
    desc="Shows information about the desired channel."
  elif cat=="voicechannel":
    ti="voicechannel [Channel Name or ID]"
    desc="Shows information about the desired Voice Channel."
  elif cat=="user":
    ti="user [User Name, Nickname, ID or Mention] [Channel Name, ID or Mention]"
    desc=f"Shows information about the desired User in a specific channel.\nThe arguments are optional."
  elif cat=="uservoice":
    ti="uservoice [User Name, Nickname, ID or Mention] [Channel Name or ID]"
    desc="Shows information about the desired User in a specific voice channel."
  elif cat=="avatar":
    ti="avatar [User Name, Nickname, ID or Mention]"
    desc="Shows the avatar of the desired user."
  elif cat=="invite":
    ti="voicechannel [Invite link or ID]"
    desc="Shows information about the desired invite link."
  elif cat=="template":
    ti="template [Template ID]"
    desc=f"Shows information about the desired server template.\nThis command is still in BETA."
  elif cat=="spam":
    ti="spam [Number of times to spam] [Text to spam]"
    desc=f"Spams the text.\nIt must be less than 30 times and without any mentions."
  elif cat=="embed":
    ti="embed [Title] [Description] [Color]…"
    desc=f"Generates an embed.\n**One line for each argument.**\nPlease check the [documentation](https://github.com/johann-lau/Bot#embed-message-help) for more information."
  elif cat=="pretend":
    ti="pretend [User Name, Nickname, ID or Mention] [Text]"
    desc="Pretends as a user and send something, using the magic of webhooks."
  elif cat=="pretendembed":
    ti="pretendembed [User Name, Nickname, ID or Mention] [Title] [Description] [Color]…"
    desc=f"Pretends as a user and generates an embed.\n**One line for each argument.**\nPlease check the [documentation](https://github.com/johann-lau/Bot#embed-message-help) for more information."
  elif cat=="pretendspam":
    ti="pretendspam [User Name, Nickname, ID or Mention] [Text]"
    desc=f"Pretends as a user and spams the text.\nIt must be less than 30 times and without any mentions."
  elif cat=="insert":
    ti="insert [Emoji] [Text]"
    desc=f"Replaces the spaces in the text with emojis.\nProtip: also works with multiple emojis by wrapping all emojis in quotation marks. E.g. `=insert \":thumbsup: :heart:\" I love this bot!`"
  elif cat=="spoiler":
    ti="spoiler [Text]"
    desc="Generates an annoying spoiler."
  elif cat=="rawspoiler":
    ti="rawspoiler [Text]"
    desc="Generates an annoying spoiler for you to copy and paste."
  elif cat=="reverse":
    ti="reverse [Text]"
    desc="sesrever the provided text."
  elif cat=="emoji":
    ti="emoji [Text]"
    desc=f"Generates emoji text.\nSupported characters: A-Z a-z 0-9 ! ? $ # * + - × ÷"
  elif cat=="kick":
    ti="kick [User Name, Nickname, ID or Mention] {Reason}"
    desc="Kicks a desired user. The Reason is optional."
  elif cat=="ban":
    ti="ban [User Name, Nickname, ID or Mention] {Reason}"
    desc="Bans a desired user. The Reason is optional."
  elif cat=="slowmode":
    ti="slowmode [Seconds] {Channel(s)}"
    desc=f"Sets the slowmode for the channel. Any non-numeric value, or zero, disables it.\nChannels is optional. If Channel(s) is not provided, the current channel will be set.\nYou are allowed to use multiple channels, or use `all` to set for all channels in the server."
  elif cat=="nick":
    ti="nick [New nickname]"
    desc=f"Sets the nickname of the bot."
  elif cat=="calc":
    ti="calc [Formula]"
    desc="Does boring math for you. Logical comparisons, scientific math, variables and user-defined functions are available. Please check the [documentation](https://github.com/johann-lau/Bot/blob/main/README.md#math-help) for more information."
  elif cat=="define":
    ti="define [name] [definition] [arguments separated by spaces]"
    desc="Defines a custom function. Please check the [documentation](https://github.com/johann-lau/Bot/blob/main/README.md#math-help) for more information."
  elif cat=="time":
    ti="time {Timezone}"
    desc="Checks the time in your timezone. If Timezone is not specified, you will see the UTC time."
  elif cat=="rtimer":
    ti="rtimer [Time to count] {Text}"
    desc=f"Starts a timer. Use `s` (seconds), `m` (minutes), `h` (hours), `d` (days) and `w` (weeks).\nIf you specify a unit twice (e.g. `10s5s`), the first one will be omitted.\nDefault to seconds if no unit is specified.\nThe Text is optional."
  elif cat=="terminate":
    ti="terminate [Timer ID]"
    desc=f"Properly terminates a running timer generated by `rtime`.\nThe Timer ID is a random 5-alphabet code and can be found at the beginning of a timer."
  elif cat=="translate":
    ti="translate [To lang]{,From lang} [Text]"
    desc="Translates text to another language. If From language is not provided, it will detect the language. e.g. `=translate en Ahoj` `=translate en,cs Ahoj`"
  elif cat=="timer":
    ti="timer [Seconds] {Text}"
    desc=f"Starts a timer. The Text is optional.\n**Alert: This command is outdated. Consider using** `rtimer` **instead.**"
  elif cat=="screenshot":
    ti="screenshot [URL]"
    desc="Screenshots the desired webpage. A regular-sized screenshot and a whole-webpage-sized screenshot will be shown."
  elif cat=="youtube":
    ti="youtube [URL]"
    desc="Downloads a youtube video and the captions. If the video size is larger than 8MB, only the captions will be uploaded."
  elif cat=="wiki":
    ti="wiki [Query]"
    desc="Finds a related Wikipedia article."
  elif cat=="engrave":
    ti="engrave [Product] [Text]"
    desc="Engraves the text on an Apple Product. Airpods, iPad, iPod and Apple Pencil are available. Please check the [documentation](https://github.com/johann-lau/Bot/blob/main/README.md#apple-engrave-help) for more information."
  elif cat=="python":
    ti="python [Python script]"
    desc="Executes a Python (3.9.1) script."
  elif cat=="ocr":
    ti="ocr [Image]"
    desc=f"Does an OCR scan for the image."
  elif cat=="text":
    ti="text [PDF]"
    desc=f"Turns the PDF to plain text."
  else:
    ti="Superior Bot Help"
    desc="""
**Prefix: **`=`

**Basic Commands**
`help` `invite` `prefix` `ping` `speedtest`

**Discord Information Commands**
`server` `role` `channel` `voicechannel` `user` `uservoice` `avatar` `invite`

**Discord Commands**
`spam` `embed` `pretend` `pretendembed`

**Text Manipulation Commands**
`insert` `spoiler` `rawspoiler` `reverse` `emoji`

**Moderation**
`kick` `ban` `slowmode` `nick` `purgeregex` `purgepy` `purgepygex`

**Information Commands**
`translate` `calc` `define` `time` `rtimer` `terminate`

**Web Commands**
`screenshot` `youtube` `wiki` `engrave` `covid` `population`

**Plot commands**
`pie` `barh` `barv` `hist` `snow`

**Developer Tools and Others**
`python` `transparent` `ocr` `text` `html` `md` `regex` `regsub`

Need help? check the [documentation](https://github.com/johann-lau/Bot#bot-documentation)!
  """
  embed=discord.Embed(title=ti, description=desc, color=0x0061ff)
  return embed

def botinvite():
  embed = discord.Embed(title="Invite", description = "Our bot could be invited [here](https://discord.com/oauth2/authorize?client_id=796686363604680755&permissions=805399670&scope=bot).")
  return embed
